function varargout=bistable(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=3;
   return
  case 'nout'
   varargout{1}=2;
   return
  case 'argrange'
   varargout{1}=struct('t',1:1,'x',2:3,'p',4:6);
   return
  case 'argsize'
   varargout{1}=struct('t',1,'x',2,'p',3);
   return
  case 'vector'
   varargout{1}=struct('t',0,'x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=5;
   return
end
nout=2;
order=varargin{1};
f=str2func(sprintf('bistable_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2] = bistable_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%BISTABLE_RHS_0
%    [OUT1,OUT2] = BISTABLE_RHS_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 09:58:24

out1 = in3;
if nargout > 1
    t2 = -in2;
    out2 = t2+in5.*cos((in1.*pi.*2.0)./in4)-in3.*in6+in2.^2.*t2;
end
end


function [out1,out2] = bistable_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%BISTABLE_RHS_1
%    [OUT1,OUT2] = BISTABLE_RHS_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 09:58:24

out1 = in9;
if nargout > 1
    t2 = 1.0./in4;
    t3 = in1.*t2.*pi.*2.0;
    out2 = -in8-in3.*in12-in6.*in9-in2.^2.*in8.*3.0+in11.*cos(t3)-in5.*sin(t3).*(in7.*t2.*pi.*2.0-in1.*in10.*t2.^2.*pi.*2.0);
end
end


function [out1,out2] = bistable_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%BISTABLE_RHS_2
%    [OUT1,OUT2] = BISTABLE_RHS_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 09:58:24

out1 = 0.0;
if nargout > 1
    t2 = 1.0./in4;
    t3 = t2.^2;
    t4 = in1.*t2.*pi.*2.0;
    t5 = in7.*t2.*pi.*2.0;
    t6 = in1.*in10.*t3.*pi.*2.0;
    t7 = sin(t4);
    t8 = -t6;
    t9 = t5+t8;
    out2 = in9.*in12.*-2.0-in2.*in8.^2.*6.0-in5.*t7.*(in1.*in10.^2.*t2.^3.*pi.*4.0-in7.*in10.*t3.*pi.*4.0)-in5.*t9.^2.*cos(t4)-in11.*t7.*t9.*2.0;
end
end


function [out1,out2] = bistable_rhs_3(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%BISTABLE_RHS_3
%    [OUT1,OUT2] = BISTABLE_RHS_3(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 09:58:24

out1 = 0.0;
if nargout > 1
    t2 = in10.^2;
    t3 = 1.0./in4;
    t4 = t3.^2;
    t5 = t3.^3;
    t6 = in1.*t3.*pi.*2.0;
    t7 = in7.*t3.*pi.*2.0;
    t8 = cos(t6);
    t9 = in1.*in10.*t4.*pi.*2.0;
    t10 = in7.*in10.*t4.*pi.*4.0;
    t11 = sin(t6);
    t13 = in1.*t2.*t5.*pi.*4.0;
    t12 = -t9;
    t14 = -t13;
    t15 = t7+t12;
    t16 = t10+t14;
    out2 = in8.^3.*-6.0+in5.*t11.*t15.^3-in11.*t8.*t15.^2.*3.0-in5.*t11.*(in7.*t2.*t5.*pi.*1.2e+1-in1.*in10.^3.*t4.^2.*pi.*1.2e+1)+in11.*t11.*t16.*3.0+in5.*t8.*t15.*t16.*3.0;
end
end


function [out1,out2] = bistable_rhs_4(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%BISTABLE_RHS_4
%    [OUT1,OUT2] = BISTABLE_RHS_4(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 09:58:24

out1 = 0.0;
if nargout > 1
    t2 = in10.^2;
    t3 = in10.^3;
    t4 = 1.0./in4;
    t5 = t4.^2;
    t6 = t4.^3;
    t8 = in1.*t4.*pi.*2.0;
    t9 = in7.*t4.*pi.*2.0;
    t7 = t5.^2;
    t10 = cos(t8);
    t11 = in1.*in10.*t5.*pi.*2.0;
    t12 = in7.*in10.*t5.*pi.*4.0;
    t13 = sin(t8);
    t15 = in1.*t2.*t6.*pi.*4.0;
    t18 = in7.*t2.*t6.*pi.*1.2e+1;
    t14 = -t11;
    t16 = -t15;
    t17 = in1.*t3.*t7.*pi.*1.2e+1;
    t19 = -t18;
    t20 = t9+t14;
    t21 = t12+t16;
    t22 = t17+t19;
    out2 = in5.*t10.*t21.^2.*-3.0+in5.*t10.*t20.^4+in11.*t13.*t20.^3.*4.0+in5.*t13.*(in7.*t3.*t7.*pi.*4.8e+1-in1.*t2.^2.*t4.^5.*pi.*4.8e+1)+in11.*t13.*t22.*4.0+in5.*t10.*t20.*t22.*4.0+in11.*t10.*t20.*t21.*1.2e+1-in5.*t13.*t20.^2.*t21.*6.0;
end
end


function [out1,out2] = bistable_rhs_5(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%BISTABLE_RHS_5
%    [OUT1,OUT2] = BISTABLE_RHS_5(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 09:58:24

out1 = 0.0;
if nargout > 1
    t2 = in10.^2;
    t3 = in10.^3;
    t5 = 1.0./in4;
    t4 = t2.^2;
    t6 = t5.^2;
    t7 = t5.^3;
    t9 = t5.^5;
    t10 = in1.*t5.*pi.*2.0;
    t11 = in7.*t5.*pi.*2.0;
    t8 = t6.^2;
    t12 = cos(t10);
    t13 = in1.*in10.*t6.*pi.*2.0;
    t14 = in7.*in10.*t6.*pi.*4.0;
    t15 = sin(t10);
    t17 = in1.*t2.*t7.*pi.*4.0;
    t20 = in7.*t2.*t7.*pi.*1.2e+1;
    t21 = in1.*t4.*t9.*pi.*4.8e+1;
    t16 = -t13;
    t18 = -t17;
    t19 = in1.*t3.*t8.*pi.*1.2e+1;
    t22 = in7.*t3.*t8.*pi.*4.8e+1;
    t23 = -t20;
    t24 = -t22;
    t25 = t11+t16;
    t27 = t14+t18;
    t29 = t19+t23;
    t26 = t25.^2;
    t28 = t27.^2;
    t30 = t21+t24;
    out2 = -in5.*t15.*t25.^5+in11.*t12.*t26.^2.*5.0-in5.*t15.*(in7.*t4.*t9.*pi.*2.4e+2-in1.*in10.^5.*t6.^3.*pi.*2.4e+2)-in11.*t12.*t28.*1.5e+1-in11.*t15.*t30.*5.0-in5.*t12.*t25.*t30.*5.0-in5.*t12.*t27.*t29.*1.0e+1+in5.*t15.*t25.*t28.*1.5e+1-in5.*t15.*t26.*t29.*1.0e+1+in11.*t12.*t25.*t29.*2.0e+1-in11.*t15.*t26.*t27.*3.0e+1-in5.*t12.*t25.^3.*t27.*1.0e+1;
end
end

